apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: socket-server-pod-reader-binding
  namespace: spark
subjects:
- kind: ServiceAccount
  name: socket-server
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
