apiVersion: v1
kind: ServiceAccount
metadata:
  name: socket-server
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: socket-server-sparkapplication
rules:
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications"]
  verbs: ["create", "get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: socket-server-sparkapplication-binding
subjects:
- kind: ServiceAccount
  name: socket-server
  namespace: default
roleRef:
  kind: ClusterRole
  name: socket-server-sparkapplication
  apiGroup: rbac.authorization.k8s.io
