apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server
  namespace: default
  labels:
    app: socket-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      serviceAccountName: socket-server
      containers:
      - name: socket-server
        image: socket-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: socket-server
spec:
  selector:
    app: socket-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
