apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sparkapplications.sparkoperator.k8s.io
spec:
  group: sparkoperator.k8s.io
  names:
    kind: SparkApplication
    listKind: SparkApplicationList
    plural: sparkapplications
    singular: sparkapplication
  scope: Namespaced
  versions:
  - name: v1beta2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              type:
                type: string
              mode:
                type: string
              image:
                type: string
              mainApplicationFile:
                type: string
              arguments:
                type: array
                items:
                  type: string
              driver:
                type: object
                properties:
                  cores:
                    type: integer
                  memory:
                    type: string
                  serviceAccount:
                    type: string
              executor:
                type: object
                properties:
                  cores:
                    type: integer
                  memory:
                    type: string
                  instances:
                    type: integer
          status:
            type: object
            properties:
              applicationState:
                type: object
                properties:
                  state:
                    type: string 